Common components and Sign in with Apple module
surfstudio/ThirdPartyAuth pull request #1
Opened 2023-04-22 14:24 UTC by AdmiralBizon

# Что сделано

- Добавлен модуль авторизации через Apple ID
- Добавлены UI-компоненты для основных элементов библиотеки: ThirdPartyAuthTitleContainer, ThirdPartyAuthButtonContainer, ThirdPartyAuthButton
- Добавлен enum с доступными способами авторизации (сейчас это Apple, Google и VK)
- Добавлена русская и английская локализация
- Добавлены вспомогательные базовые элементы для внутренней логики
- Добавлен ReadMe с описанием основного функционала

# На что обратить внимание

- Для уменьшения количества самописного кода затянута библиотека [iOS-Utils](https://github.com/surfstudio/iOS-Utils) версии 13.2.0

[ReadMe с описанием](https://github.com/AdmiralBizon/ThirdPartyAuth/tree/add-apple-auth)

2023-04-24 12:11 UTC, chausovSurfStudio requested changes
резюмирую, что самое главное

- убедиться что вечного лоадера не будет при любом раскладе
- точно ли всех данных, которые нам возвращает либа, хватит для реальной авторизации через apple sign in? (как она вообще работает? не надо ли еще каких-то полей из той системной модельки передать?)
- сделать публичными вещи, которые позволят авторизоваться без использования UI
- добавить комментов
- выпилить шрифты и возможно завязку на Utils

 а все остальное, в том числе визуальную кастомизацию UI, можно уже на потом оставить

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Common/Views/TitleContainer/ThirdPartyAuthTitleContainer.swift
> +
как вариант, чтобы добавить немного кастомизации - можно сделать в будущем методы для установки текста (может кому-то "Или" не подойдет) и для установки цветов текста/линий

и вот с цветом текста возможно будет тяжко, потому предложил бы рассмотреть такой вариант

точно ли тут нужна завязка на утилиты (iOS-Utils)? как бы с точки зрения чистоты кода - все красиво, но тянуть лишнюю зависимость ради стилей, в библиотеке, которая не про UI, а скорее про логику - кажется излишним... в общем, подумай над тем, чтобы избавиться от стилей и немного упростить все это дело) и тогда, если стилей не будет, но можно будет в легкую менять цвет текста через label.textColor -> можно будет сделать такую возможность для кастомизации

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Common/Views/TitleContainer/ThirdPartyAuthTitleContainer.swift
> +
ага, стили и CommonButton

ну да, понимаю желание переиспользовать код, да) но предложил бы облегчить либу, тем более велика вероятность, что UI на проектах будет свой поверх логики навешиваться

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Resources/Colors/Colors.swift
> +        static let border = Styles.Colors.Buttons.border.color
а затяни тогда уж и сюда темные цвета для этой кнопки из темной палитры проекта)

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Resources/Fonts/Fonts.swift
> +@available(*, deprecated, renamed: "FontConvertible.Font", message: "This typealias will be removed in SwiftGen 7.0")
во, второе предложение - часто у проектов свои шрифты, и тут опять же - не угадаешь какой шрифт где нужен) если ты сделаешь кастомизацию в будущем, и дашь возможность менять шрифт в лейбле "Или" - то необходимость в этом кастомном шрифте отпадет

потому предложил бы пока не тянуть сюда кастомный шрифт, все же лишние 259кб)) и заюзать обычный системный, который больше похож на текущий

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Resources/Images/Images.xcassets/Icons/google.imageset/Contents.json
> +    "preserves-vector-representation" : true
ай молодец что галочку проставил эту)

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Common/Protocols/BaseCredentialsService.swift
> +protocol BaseCredentialsService {
я вот пока сути этого протокола не понял... вроде он используется в `AppleCredentialsService`, а тот в свою очередь не используется нигде(( какая задумка?

и предложил бы комменты ко всем публичным и "общим" вещам написать, а то потом концов не найдем во время поддержки)

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Common/Models/ThirdPartyAuthUserModel.swift
> +        self.id = appleIDCredential.user
а вообще как в жизни работает apple sign in рассматривал? то есть что реально может потребоваться бэку для такой авторизации? хватит ли ему этих данных?

а то в `appleIDCredential` есть такие интересные поля как `authorizationCode` и `identityToken` - они нам точно не пригодятся?

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Apple/Providers/AppleAuthProvider.swift
> +        }
выглядит так, что надо переписать на guard и в случае, если `authorization.credential as? ASAuthorizationAppleIDCredential` не прокатит - вызвать `onAuthFinished?(.failure(error))` (только вот что передать в качестве ошибку... какую-то свою, типа ThirdPartyAuth.invalidCredentials?)

что пугает - если скастить `authorization.credential` не получится к нужному типу - не будет ли у нас "вечного лоадера" на кнопке?

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Apple/Providers/AppleAuthProvider.swift
> +        }
ну в общем подумай, что тут происходит, и не может ли оно сломаться)

2023-04-24 12:11 UTC, chausovSurfStudio commented on ThirdPartyAuth/Common/Views/ButtonsContainer/Container/ThirdPartyAuthButtonContainerModel.swift
> +                buttonWidth: CGFloat = 56) {
вот здесь вот можно будет подумать и объединить параметры для кастомизации контейнера в одну группу, может в них еще подгруппу для кастомизации самих кнопок...

2023-04-27 07:01 UTC, AdmiralBizon commented on ThirdPartyAuth/Common/Models/ThirdPartyAuthUserModel.swift
> +        self.id = appleIDCredential.user
да, тут ты прав
я погорячился, когда изначально их выбросил из возвращаемой модели

теперь возвращаем только эти поля + id (этого достаточно для авторизации), передаем бэку, а он уже их обрабатывает - создает новую учетку или авторизует пользователя.

2023-04-27 07:12 UTC, AdmiralBizon commented on ThirdPartyAuth/Apple/Providers/AppleAuthProvider.swift
> +        }
Поле credential закрыто протоколом ASAuthorizationCredential - это общий протокол, на который подписаны все виды креденшиалов (AppleIDCredential, PasswordCredential и т.д). На сколько я понял, возможный конкретный тип этого поля зависит от того, какие типы запросы мы передадим в ASAuthorizationController:
```
let request = ASAuthorizationAppleIDProvider().createRequest()
request.requestedScopes = [.fullName, .email]

let authorizationController = ASAuthorizationController(authorizationRequests: [request])
```

В нашем случае используется только тип `ASAuthorizationAppleIDProvider`, который в результате успешной авторизации вернет значение с типом `ASAuthorizationAppleIDCredential`, поэтому какие-то доп. проверки, мне кажется, не понадобятся и вечного лоадера быть не должно.

2023-04-27 07:42 UTC, AdmiralBizon commented on ThirdPartyAuth/Common/Protocols/BaseCredentialsService.swift
> +protocol BaseCredentialsService {
Убрал этот протокол и перенес метод `checkCredentialsState` в `AppleAuthProvider`. Вообще этот метод нужен для того, чтобы проверить текущий статус авторизации для пользователя с указанным id (в этом случае после авторизации нам нужно сохранять в KeyChain полученный идентификатор, чтобы потом можно было его быстро вытащить).

Основной сценарий использования во всех примерах для этого метода - это понять текущий статус пользователя (авторизован / нет) и в зависимости от этого отрисовать UI, открыть флоу авторизации или основное флоу и т.д.
Сам метод в API возвращает один из нескольких статусов (на скрине), но мне кажется, достаточно будет того, что `state != .authorized` --> пользователь не авторизован.
Мне кажется, от него есть польза, когда вся авторизация в приложении завязана на Sign in with Apple, но в шаблонном проекте, если я правильно понял, уже есть своя схема проверки статуса авторизации через флаг `isAuthorized`, поэтому использование этого метода будет лишним наверное.
Но как метод внутри библиотеки может пригодиться.

<img width="600" src="https://user-images.githubusercontent.com/72994567/234792320-0b0c6a30-f17d-450f-9469-56f986c0a19e.png">

2023-04-27 07:46 UTC, AdmiralBizon commented
Основные изменения:
- разбил проект на 2 основных блока - ThirdPartyAuth и ThirdPartyAuthUI
- убрал шрифты и библиотеку Utils
- добавил отдельные модели для кастомизации ThirdPartyAuthTitleView (можно задать цвет сепараторов, текст лейбла и его цвет)
- конфигурацию кнопок авторизации вынес в отдельную модель, внутри которой можно настроить размер и cornerRadius
- изменил структуру моделей, возвращаемых в качестве результата авторизации

2023-05-04 16:26 UTC, chausovSurfStudio approved these changes
на UI особо не глядел, но вроде норм
но надо будет потом уже какой-нибудь example проект сделать)

в целом уже окъ выглядит, по интерфейсу либы уже потом можно будет подомуть еще раз, когда больше вариантов авторизации будет

2023-05-04 16:26 UTC, chausovSurfStudio commented on Package.swift
> +        .library(name: "ThirdPartyAuthUI", targets: ["ThirdPartyAuthUI"])
к слову говоря о разделении: текущий подход судя по всему не робит, в проект ты затаскивал просто ThirdPartyAuth, но там и ThirdPartyAuthUI подтянулись) не в курсе как решать такую проблему? просто я нет)

сейчас по идее похожей задачей Никита Гагаринов на НодКите занимается
<img width="831" alt="Снимок экрана 2023-05-04 в 18 42 53" src="https://user-images.githubusercontent.com/8776643/236259311-866ac3b6-ec7c-448c-a466-15ead53df297.png">

2023-05-04 16:26 UTC, chausovSurfStudio commented on Sources/ThirdPartyAuth/Library/Protocols/UserDataModel.swift
> +public protocol UserDataModel {}
у меня пока большое сомнение в необходимости данного протокола, потому что он пуст, в силу чего ценности не несет(

но давай оставим, как остальные соцсети будут - поглядим, что между ними будет общего, и там уже придумаем что-то на месте

2023-05-04 16:26 UTC, chausovSurfStudio commented on Sources/ThirdPartyAuth/Flows/Apple/Providers/Support/AppleAuthHandler.swift
> +        }
ну меня лично так и тянет здесь на guard написать, чтоб прям совсем спать спокойной и быть уверенным, что все пройдет как надо) читал объяснение твое, но все равно покоя не дает

внимание на изменения в коде - guard и enum ошибки
<img width="1512" alt="Снимок экрана 2023-05-04 в 18 56 54" src="https://user-images.githubusercontent.com/8776643/236263490-4d514471-a3be-4cbd-bff3-665fcf617bc9.png">

2023-05-05 19:56 UTC, AdmiralBizon commented on Sources/ThirdPartyAuth/Flows/Apple/Providers/Support/AppleAuthHandler.swift
> +        }
Так и поправил, изменения подлил в эту ветку. Проверил шаблон - проект собирается, все ок.

2023-05-05 20:02 UTC, AdmiralBizon commented on Sources/ThirdPartyAuth/Library/Protocols/UserDataModel.swift
> +public protocol UserDataModel {}
У меня тут была идея в том, чтобы библиотека возвращала одинаковую модель для всех типов авторизации вида:
- тип авторизации (apple, vk, google)
- данные пользователя (id, токены, еще что-нибудь)

Т.к. набор полей в данных пользователя отличается для разных способов авторизации, подумал, что можно сделать отдельную модельку для каждой соц. сети со своими полями и подписать ее на пустой протокол UserDataModel, которым же закрыть поле с данными пользователя в общей модели.

И получится примерно такая схема: авторизуемся -> в приложение от сервера прилетает модель (authType, UserDataModel) -> пытаемся кастить данные в нужный тип (если authType = .apple, то кастим UserDataModel в AppleAuthUserModel, например) -> если получилось, отдаем данные бэку.

2023-05-05 20:13 UTC, AdmiralBizon commented on Package.swift
> +        .library(name: "ThirdPartyAuthUI", targets: ["ThirdPartyAuthUI"])
Попробовал немного поресерчить на эту тему - не нашел каких-то примеров, чтобы затягивались только отдельные компоненты из пакета (как в нашем случае, например, только ThirdPartyAuth отображался в структуре).

Но в итоге наткнулся вот на какую штуку. 
Если при добавлении пакета поставить галочку только у ThirdPartyAuth, то сама структура пакета будет полной (как на твоем скрине), но при этом в списке добавленных к таргету либ будет только ThirdPartyAuth:

<img width="700" alt="Снимок экрана 2023-05-05 в 22 43 48" src="https://user-images.githubusercontent.com/72994567/236559286-dac1d0bf-75b6-42e3-a177-5e2b6327701a.png">

И при попытке в каком-то файле заимпортить ThirdPartyAuthUI, вылезет ошибка, что такой модуль не найден:

<img width="700" alt="Снимок экрана 2023-05-05 в 22 44 20" src="https://user-images.githubusercontent.com/72994567/236559469-a1f8aacb-76b6-4772-b2c5-f8d7d2643050.png">

После добавления ThirdPartyAuthUI в список либ нужного таргета, ошибка пропадает.

2023-05-11 07:39 UTC, chausovSurfStudio commented on Package.swift
> +        .library(name: "ThirdPartyAuthUI", targets: ["ThirdPartyAuthUI"])
забавное наблюдение) но проблем, жалко, не сильно решает, я тебе тогда в личке подробнее распишу, в чем на НодКит беда

2023-05-11 07:40 UTC, chausovSurfStudio commented on Sources/ThirdPartyAuth/Library/Protocols/UserDataModel.swift
> +public protocol UserDataModel {}
давай я пока к себе это запишу, и если что - в следующем ПРе уже подумаем еще раз, к тому же он уже есть)

2023-05-11 07:43 UTC, chausovSurfStudio approved these changes

2023-05-11 07:46 UTC, merged